version: 2
updates:

# Config for AMP plugin.
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "17:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "17:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
  # Cannot upgrade until @wordpress/element supports react v17.
  - dependency-name: react
    versions:
    - ">= 17"
  # Updates are handled via the `gutenberg-packages-update` GHA workflow.
  - dependency-name: "@wordpress/*"

# Config for GitHub Actions.
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "17:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
