version: 2
updates:
    # Config for AMP plugin.
    - package-ecosystem: composer
      directory: '/'
      schedule:
          interval: weekly
          time: '17:00'
          timezone: America/Los_Angeles
      open-pull-requests-limit: 10

    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: weekly
          time: '17:00'
          timezone: America/Los_Angeles
      open-pull-requests-limit: 10
      ignore:
          # Use same as @wordpress/element.
          - dependency-name: react
            versions:
                - '>= 18'
          # Updates are handled via the `gutenberg-packages-update` GHA workflow.
          - dependency-name: '@wordpress/*'

    # Config for GitHub Actions.
    - package-ecosystem: github-actions
      directory: '/'
      schedule:
          interval: weekly
          time: '17:00'
          timezone: America/Los_Angeles
      open-pull-requests-limit: 10
