# See documentation at https://docs.codecov.io/docs/codecovyml-reference

coverage:
    status:
        # Patch-level coverage (how well is the PR tested)
        patch:
            default:
                threshold: 75%

        # Project-level coverage
        project:
            default:
                target: auto
                threshold: 0.1%
            php:
                paths:
                    - includes
                    - src
                threshold: 0.1%
            js:
                paths:
                    - assets/src
                threshold: 0.1%

# Pull request comments
# See https://docs.codecov.io/docs/pull-request-comments
comment:
    layout: 'reach, diff, flags, files'
    behavior: default
    require_changes: true
    branches:
        - 'develop'
    # Wait for Jest & PHPUnit & Behat reports before commenting
    after_n_builds: 3

# See https://docs.codecov.io/docs/ignoring-paths
ignore:
    - '/bin'
    - '/back-compat'
    - '/docs/**/*'
    - '.phpstorm.meta.php'
    - '/includes/ecosystem-data/*'
